[package]
name = "naive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
bigdecimal = { version = "0.3.0", features = ["serde"] }
dotenv = "0.15.0"
ethers = "2.0.4"
primitives = { version = "0.1.0", path = "../../crates/primitives" }
serde = "1.0.160"
sqlx = { version = "0.6.3", features = ["macros", "migrate", "postgres", "runtime-tokio-native-tls", "bigdecimal"] }
thiserror = "1.0.40"
tokio = { version = "1.28.0", features= ["full"] }

